### ISSUE TITLE
Show a Map

### ISSUE THREAD

**Issue by tomosaigon** [PlantaFi/plantation#29]
- render info about multiple plots of Land in a grid (map)
- controls for shifting the view of which plots to render
- Land is selectable to bring up more info about Land
- so ideally Land contract can do like function getPlantSurroundings(tokenId, distance) returns (array of land info, basic plant info) - distance of 5 means all land where x and y coordinates are within +/- 5 tiles from your token

**Comment by SamiraElhami** [comment]
might need more changes after deploying on the chain.
