### ISSUE TITLE
Plant contract should be able to mint new Fruit supply and own it

### ISSUE THREAD

**Issue by tomosaigon** [PlantaFi/plantation#38]
Plants will increase Fruit supply in order to produce the requested harvest. Fruit is meant to go into the Pair (pool) when a Plant is fertilized, with less taken out if harvesting prematurely. If harvesting late then there's a staking bonus which needs to mint extra Fruit supply.

**Comment by The-Wary-One** [comment]
Is your idea really compatible with the uniswapV2Pair design ? Can we really just mint new tokens and add them to a Pair liquidity ? I thought we should only provide a 50-50 Fruit/Matic liquidity.

**Comment by tomosaigon** [comment]
Minting new tokens is up to Fruit contract implementation.

Adding new tokens to a pair should be possible by transferring the tokens to the Pair and optionally calling sync() on the pair. I don't think there's such a requirement when giving tokens to the pool. We don't need to mint LP tokens from the added liquidity.

**Comment by tomosaigon** [comment]
```    function mintFlowers(uint256 amount) public {
        _mint(address(plant), amount);
    }
```
